---
name: Test

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: osism/openstack-action@main
      - uses: actions/setup-python@v4
      - run: pip3 install python-openstackclient==6.0.0
      - run: openstack --os-cloud openstack catalog list
